spring:
  datasource:
    url: jdbc:mariadb://localhost:3306/grocery
    username: root
    password: banana
    driver-class-name: org.mariadb.jdbc.Driver
  jpa:
    hibernate:
      ddl-auto: update
server:
  error:
    include-exception: false
    include-stacktrace: never
    include-message: never